### ISSUE TITLE
endpointdowm

### ISSUE THREAD

**Issue by liaoming999** [earthquakesan/palmetto-py#5]
I am getting this following error:
Traceback (most recent call last):
  File "/Users/liaoming/Documents/Normalization/normalization/test/88.py", line 5, in <module>
    palmetto.get_coherence(words, coherence_type="cv")
  File "/Users/liaoming/Documents/eone/lib/python2.7/site-packages/palmettopy/palmetto.py", line 104, in get_coherence
    return self._get_coherence(words, coherence_type)
  File "/Users/liaoming/Documents/eone/lib/python2.7/site-packages/palmettopy/palmetto.py", line 92, in _get_coherence
    coherence = self._request_by_service(words, coherence_type)
  File "/Users/liaoming/Documents/eone/lib/python2.7/site-packages/palmettopy/palmetto.py", line 31, in _request_by_service
    raise EndpointDown(request_uri)
palmettopy.exceptions.EndpointDown

Does it mean the server is down?

**Comment by earthquakesan** [comment]
@liaoming999 was down, works again now. The service is under heavy load at times and can be unresponsive. Thanks for heads up.
